### ISSUE TITLE
Functions with underlining

### ISSUE THREAD

**Issue by ghost** [Petewg/harbour-core#6]
Hi Pete, 

Your project is a good job, thank you very much.
Please tell me about the functions:
__Accept
__AcceptStr
__AtClear
__AtPrompt
__Box
__BoxD
__BoxS
e.t.c
I do not see it in your project

- Rafał

**Comment by Petewg** [comment]
Hi Rafał,
I cannot tell you much about aforementioned functions. Although I'm aware of their existence, I never have used them, mainly due to an old "rule" according to which, functions starting with leading double (or single)  underscore, should consider as internals that not meant for end-user consumption [due to the fact that their name may change in future, for example, but also other more serious reasons)
--Ok, name-change is not quite probable to happen, given that Harbour's development is in stagnant mode, but the "rule" is still valid].

On the other hand, if you want, you can contribute documentation for them. This can be done either by sending to me a brief description (similar to any other functions found in this wiki) or by editing wiki directly, yourself. In the later case ( which i do prefer :->) I'll have to add your github account to collaborators. It's up to you, just let me know.

--
Pete

**Comment by rjopek** [comment]
I use these functions in my projects, for example:
__CopyFile( "np.dbf", "tmp.dbf" )

On the other hand, I try to avoid Commands
COPY FILE ( "np.dbf" ) TO ( "tmp.dbf" )
I think that this is an outdated model of function interpretation Commands
https://github.com/vszakats/harbour-core/blob/master/include/std.ch#L289

Regarding help in the construction of this project I do not know if I'll be able to help


Rafał

**Comment by Petewg** [comment]
__CopyFile() beyond being undocumented, isn't also a reliable function. It returns inconsistent values: `NIL` on success, `.F.` on failure.
I'd recommend using the more elegant/neat [**Harbour FILE IO**](https://github.com/Petewg/harbour-core/wiki/hb_V#harbour-file-io-functions) family of functions, 
and in this case: `hb_vfCopyFile( <cFileSrc>, <cFileDst> ) ➜ nResult` would be ideal.

Regarding **commands vs functions** usage: I think both models have advantages/disadvantages. Commands offer simplicity/readability, functions offer greatest flexibility. Commands cannot be used in code-blocks or as expressions, functions are syntactically more complex hence more difficult in typing/remembering. We could list more pros/cons. Eventually, it all depends on 'what' and 'where' you choose to use and of course it's a matter of preferred programming style (pure subjective thing!). 
However, I do not think that 'Command-model' is outdated! Many modern and highly successful languages do use commands.

PS. Me too I didn't know if I would be able to create documentation, (and at times in the past, I used to complain about the lack of docs, into harbour-users group). And then I tried to create this wiki that, hopefully, brought in some no bad results.

--Pete
